language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
  - openjdk11
git:
  submodules: false
before_install:
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ./paper jar
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/Minecraft'
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "./*.jar"
  on:
    tags: true
